### ISSUE TITLE
Is this code being maintained? 

### ISSUE THREAD

**Issue by rturk** [mikberg/relay-mongodb-connection#1]
Hi @mikberg,
This code is amazing. However looks like is almost 7 months old. Meanwhile there where a few newer GraphQL/Relay releases. 
Can you comment?
Tks

**Comment by mikberg** [comment]
Hi! I haven't had any personal use for it in half a year, so I haven't maintained it in this period. I haven't tested whether it works with newer releases of graphql and relay. PRs welcome.
