### ISSUE TITLE
version 2.0 breaking the code

### ISSUE THREAD

**Issue by du5rte** [mikberg/relay-mongodb-connection#3]
Hi, first of all great module! been using it for a while and it's good to see an update 😊

Looks like there's some code not being compiled correctly on the new version

``` sh
... /node_modules/relay-mongodb-connection/lib/index.js:3
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

I've tracked it down to a few `import` statements on `lib/index.js`

``` js
import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
import _Object$keys from 'babel-runtime/core-js/object/keys';
```

It should be

``` js
var _Object$defineProperty = require('babel-runtime/core-js/object/define-property').default;
var _Object$keys = require('babel-runtime/core-js/object/keys').default;
```

**Comment by mikberg** [comment]
Thanks for opening the issue! Sorry about the problem, this package really shouldn't use Babel in the first place. I'll try to take a look at it this weekend.

**Comment by papigers** [comment]
@mikberg Any chance the issue is that `.babelrc` is on `.npmignore` and so the src doesn't get compiled right? or the code is compiled before you even publish it to npm?

**Comment by mikberg** [comment]
I went on a little adventure today and tried get rid of Babel, but ran into a bunch of problems. Sorry about this taking some time.

**Comment by mikberg** [comment]
@papigers Not sure. Kind of not too keen on releasing a new version before rewriting to getting rid of Babel.

**Comment by papigers** [comment]
@mikberg I worked on removing babel, and I think I got everything work (tests are fine).
I'm just gonna make sure and check it on my own project I'm working on. If everything is well, expect a PR soon :)

**Comment by mikberg** [comment]
@papigers Awesome!
