### ISSUE TITLE
[question] how to handle pagination when the dataset is not static?

### ISSUE THREAD

**Issue by sibelius** [mikberg/relay-mongodb-connection#6]
```
/**
 * Accepts a mongodb cursor and connection arguments, and returns a connection
 * object for use in GraphQL. It uses array offsets as pagination, so pagination
 * will work only if the data set is static.
 */
```

how can I handle pagination if my data set is not static?

My use case is very simple and common, I have a list of items, then using a mutation somebody can  create a new item inside this list

How to handle this case in Relay? should I do a forceFetch ?

**Comment by mikberg** [comment]
I'd say the simplest thing you could do is to just include the entire list in your fat query, with a `FIELDS_CHANGE` config. That way the list should be downloaded fresh every time you run the mutation.

```
getFatQuery() {
    return Relay.QL`
      fragment on MyMutation {
        viewer {
          myList
        }
      }
    `;
  }
getConfigs() {
    return [{
      type: 'FIELDS_CHANGE',
      fieldIDs: {
        viewer: this.props.viewer.id,
      },
    }];
  }
```

**Comment by sibelius** [comment]
this works tks

sorry for delay in my response
